name: Run Tests

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:alpine
        env:
          POSTGRES_USER: user
          POSTGRES_PASSWORD: password
          POSTGRES_DB: dbname
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build Docker image
        run: docker build -t movie-explorer:latest .

      - name: Run backend tests
        run: |
          docker run --rm \
            --network host \
            -e DATABASE_URL=postgresql://user:password@localhost:5432/dbname \
            movie-explorer:latest \
            sh -c "PYTHONPATH=. pytest -vvv"

      - name: Run frontend tests
        run: |
          docker run --rm movie-explorer:latest sh -c "cd /frontend && npm install && npm run test"
